### ISSUE TITLE
The license is not licensed.

### ISSUE THREAD

**Issue by Michagogo** [jakimfett/MMPLv2#10]
There is no license applied to this license. This means that all copyrights in the license are owned by the authors of the various parts, and all rights are reserved, other than those [released in the GitHub terms of service](https://help.github.com/articles/github-terms-of-service/#f-copyright-and-content-ownership). To fix this, you'd need to get all authors of/contributors to any part of the license to agree to release it under a license of some sort.

**Comment by Strikingwolf** [comment]
Any progress on the perms?

**Comment by jakimfett** [comment]
Nothing so far. Maybe @asiekierka can ping @spacetoad again? I know spacetoad was busy with IRL stuff, so it may be a bit.

**Comment by Strikingwolf** [comment]
Also, I still think that the MIT license would be a great fit for this

**Comment by jakimfett** [comment]
So here's a thought...the current version of the license is almost 100% different (I did a diff, and the only things that are the same are three headings for sections) than the MMPLv1...given that it's a complete rewrite at this point, do we need to get permission from spacetoad?

I'm honestly not sure how copyright applies to text that technically started as a derivative, but no longer has any of the original text.

**Comment by Strikingwolf** [comment]
I think it would fall under significant changes. I say we go ahead and license it under MIT

**Comment by cuchaz** [comment]
If we're not sharing any text with the original license, then there's no copyright infringement.

It would be kind of a nice gesture to credit the original license as inspiration for this one though.

**Comment by jakimfett** [comment]
Definitely going to credit the original license. It was a good solid inspiration for the MMPLv2, and I'm all about credit where credit is due.

As far as which license to put this under...I'm actually considering my "Don't Be a Jerk" license. Out of curiosity, @Strikingwolf, what benefits does the MIT give us over something openly permissive, like the   WTFPL?

**Comment by cuchaz** [comment]
MIT and WTFPL are basically the same thing, except the MIT is more explicit about what rights are granted and also includes a no warranty section. I'd pick the MIT license over the WTFPL (even though I really like the WTFPL) just because it's already held up to lawyer scrutiny.

**Comment by Strikingwolf** [comment]
Basically what @cuchaz said.

**Comment by Strikingwolf** [comment]
Is this ready to license BTW

**Comment by jakimfett** [comment]
I decided on MIT for the license of the license. I'd say it's 95% ready to go, I'm still tweaking some last bits, but overall it's solid.
