### ISSUE TITLE
Modified vs. Unmodified

### ISSUE THREAD

**Issue by ljfa-ag** [jakimfett/MMPLv2#21]
It doesn't make any sense to me why distribution of unmodified versions would be more restricted than distribution of derivatives.

Someone could just go ahead and modify just a single instruction and make a derivative this way.
I suggest completely dropping the distinction between modified and unmodified versions.

In particular: "Unmodified copies may only be distributed through the link the mod author provides."
Think about it. It also means you're not allowed to fork a repository.

This is probably an unintended consequence of commit a3fdac843e41873e99428fdb9e43347e33c8b970. I understand its intended purpose: To stop the classical case of "mod reposting" where a site rehosts a mod without giving credit to the author. But this is already covered by section 6: "[...]must be distributed under the same license as this mod."

The whole section 5 as of now is too restrictive to be considered Open Source. I suggest dropping it. It even conflicts with @jakimfett 's own definition of Open Source (#9). 
Also: "The original mod author may revoke hosting permission from any distributor." Think about it. This is basically equivalent to "All Rights Reserved".
Open Source software should encourage users to modify and distribute the software and not stop them from doing so.

If you truly want to make an Open Source license then please focus on the community rather than on the individual mod author.
However if you're trying to prevent authors from "unfair use" of their code and put the rest of the community behind the "original mod author" then you're missing the purpose of Open Source.

I might be making a pull request with some suggested changes but I'm afraid it might be fruitless because you guys don't agree with me either way. I saw how close-minded you, @jakimfett, were about #9, no offense. I need to get some sleep first... see, that's how much I care about this license.

**Comment by cuchaz** [comment]
Looks like there's been lots of changes since my original PR. I don't necessarily agree with all the changes since then. When I get some time, I'll do another pass through the license and find a better way to state things.

**Comment by Strikingwolf** [comment]
@ljfa-ag remember that this is a WIP. I agree that some of the things need to be fixed. If you want to discuss it come on #stopmodreposts on esper.net

**Comment by ljfa-ag** [comment]
I know that it's a WIP. But this is the wrong direction to go,

**Comment by Strikingwolf** [comment]
@ljfa-ag like I said, it needs to be fixed

**Comment by ljfa-ag** [comment]
I'd like to discuss it. Well time zone differences suck -.-
I need to familiarize myself with IRC since I've never used it before

**Comment by ljfa-ag** [comment]
I had a small discussion with @Strikingwolf and he told me that this license was not intended to be Open Source after all.
He stated that the purpose was to forbid redistributing mods, which is incompatible with Open Source.
I'm very sorry to read that. I once again request to remove the words "Open Source" from the readme file if that's really the intention behind this license.

**Comment by jakimfett** [comment]
If the [changes I made](https://github.com/jakimfett/MMPLv2/commits?author=jakimfett) look good to everyone, I'll go ahead and close this. 

Full text is, as always, available [here](https://github.com/jakimfett/MMPLv2/blob/master/LICENSE.md)
