### ISSUE TITLE
License Changes

### ISSUE THREAD

**Issue by hilburn** [jakimfett/MMPLv2#24]
As sometimes happens with projects, people want to change licenses as the project progresses down the line and (as is currently the case with Asie and Buildcraft) this is somewhat impossible, when you then have to chase down the 50-odd people who contributed something under the old system. Even if it was a single line that has been moved and refactored so much that GitHub's blame mode can't even tell you the original author any more, so you have to contact everyone on the list.
I think a clause stating that material contributed to a project using this license can be re-licensed under another (open source) license with the majority vote of active (within the last month) contributors would be welcome

**Comment by cuchaz** [comment]
Contributor license agreements are designed to solve that problem, but there's really no place for that in a user license agreement. What rights do you grant a user to govern the rights of a third party contributor?

**Comment by hilburn** [comment]
True - but quite a lot of people use one license to cover the entire project through contribution and distribution. I thought it might be helpful to include some form of CLA that sets up some form of default agreement in the event no particular CLA is specified

**Comment by cuchaz** [comment]
Can you link an example of such a license? I haven't seen one before.

**Comment by hilburn** [comment]
Sorry - I didn't mean a license that covers both CLA and ULA - I meant that most mods don't include any form of CLA which is the root of many problems with changing things later down the line.
As such the addition of a line eg. 
>"Unless specified elsewhere, contributions to this project are covered by <Generic Contributor Assignment Agreement>" 
Would make things a bit easier imo

**Comment by cuchaz** [comment]
But that's the point I'm making... you can't cede the rights of contributors in a document describing the rights granted to an end user. If you want to use a CLA, make the contributors sign a CLA. You can't achieve the same effect in a EULA.

**Comment by hilburn** [comment]
meh
