### ISSUE TITLE
Modpacks don't have to link to original mod page

### ISSUE THREAD

**Issue by michael-3-141** [jakimfett/MMPLv2#26]
I think it would be a good idea to add linking to the mod page/forum post as a requirement for modpacks. Does anyone agree?

**Comment by cuchaz** [comment]
Yup

**Comment by michael-elgavi** [comment]
I'm not a very good writer so someone else should write a pull request

**Comment by cuchaz** [comment]
I had a big PR a while back that covered this issue (among others). I got a lot of feedback on the PR. When I get some more time, I'll write follow-up PRs to actually fix the issues.

**Comment by jakimfett** [comment]
In some contexts, this isn't possible. As Forge supports a metadata object (which can include links, author names, etc), I don't think this is necessary.

**Comment by michael-3-141** [comment]
Could we at least have a different version which does require this? I wouldn't want a licence that allows anyone to redistribute my mod without giving any credit.

**Comment by jakimfett** [comment]
I actually had a bit of an idea on how to solve this. Suffice it to say, it's going to solve a number of issues, including this one.
